In [2]:
import nltk

# Descargar el conjunto de datos 'punkt', que es necesario para la tokenización de oraciones
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\egzlz\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [6]:
nltk.data.path.insert(0, 'C:\\Users\\egzlz\\AppData\\Roaming\\nltk_data')


In [8]:
print(nltk.data.path)


['C:\\Users\\egzlz\\AppData\\Roaming\\nltk_data', 'C:\\Users\\egzlz/nltk_data', 'c:\\Users\\egzlz\\AppData\\Local\\Programs\\Python\\Python38\\nltk_data', 'c:\\Users\\egzlz\\AppData\\Local\\Programs\\Python\\Python38\\share\\nltk_data', 'c:\\Users\\egzlz\\AppData\\Local\\Programs\\Python\\Python38\\lib\\nltk_data', 'C:\\Users\\egzlz\\AppData\\Roaming\\nltk_data', 'C:\\nltk_data', 'D:\\nltk_data', 'E:\\nltk_data']


In [5]:
from transformers import BertTokenizer, RobertaTokenizer, AlbertTokenizer, T5Tokenizer, BertTokenizerFast

# Texto de ejemplo
text = "unbelievable"

# 1. WordPiece Tokenizer (BERT)
print("WordPiece Tokenizer (BERT):")
tokenizer_bert = BertTokenizer.from_pretrained('bert-base-uncased')
tokens_bert = tokenizer_bert.tokenize(text)
print(tokens_bert)

# 2. Byte-Pair Encoding (BPE) Tokenizer (RoBERTa)
print("\nByte-Pair Encoding Tokenizer (RoBERTa):")
tokenizer_roberta = RobertaTokenizer.from_pretrained('roberta-base')
tokens_roberta = tokenizer_roberta.tokenize(text)
print(tokens_roberta)

# 3. SentencePiece Tokenizer (ALBERT)
print("\nSentencePiece Tokenizer (ALBERT):")
tokenizer_albert = AlbertTokenizer.from_pretrained('albert-base-v2')
tokens_albert = tokenizer_albert.tokenize(text)
print(tokens_albert)

# 4. Unigram Tokenizer (T5)
print("\nUnigram Tokenizer (T5):")
tokenizer_t5 = T5Tokenizer.from_pretrained('t5-small')
tokens_t5 = tokenizer_t5.tokenize(text)
print(tokens_t5)

# 5. Fast Tokenizer (BERT Fast)
print("\nFast Tokenizer (BERT Fast):")
tokenizer_fast = BertTokenizerFast.from_pretrained('bert-base-uncased')
tokens_fast = tokenizer_fast.tokenize(text)
print(tokens_fast)


c:\Users\egzlz\AppData\Local\Programs\Python\Python38\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


WordPiece Tokenizer (BERT):


C:\Users\egzlz\AppData\Roaming\Python\Python38\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


['unbelievable']

Byte-Pair Encoding Tokenizer (RoBERTa):
['un', 'bel', 'iev', 'able']

SentencePiece Tokenizer (ALBERT):
['▁un', 'be', 'liev', 'able']

Unigram Tokenizer (T5):


You are using the default legacy behaviour of the <class 'transformers.models.t5.tokenization_t5.T5Tokenizer'>. This is expected, and simply means that the `legacy` (previous) behavior will be used so nothing changes for you. If you want to use the new behaviour, set `legacy=False`. This should only be set if you understand what it means, and thoroughly read the reason why this was added as explained in https://github.com/huggingface/transformers/pull/24565


['▁unbelievable']

Fast Tokenizer (BERT Fast):
['unbelievable']


In [19]:
from datasets import load_dataset, get_dataset_infos


# Para obtener más detalles de un dataset específico
dataset = load_dataset('trec',trust_remote_code=True)
print(dataset['train'][0])
train_dataset=dataset['train']
test_dataset=dataset['test']

{'text': 'How did serfdom develop in and then leave Russia ?', 'coarse_label': 2, 'fine_label': 26}


In [2]:
print(dataset['train'].features['fine_label'].names)
print(dataset['train'].features['coarse_label'].names)

['ABBR:abb', 'ABBR:exp', 'ENTY:animal', 'ENTY:body', 'ENTY:color', 'ENTY:cremat', 'ENTY:currency', 'ENTY:dismed', 'ENTY:event', 'ENTY:food', 'ENTY:instru', 'ENTY:lang', 'ENTY:letter', 'ENTY:other', 'ENTY:plant', 'ENTY:product', 'ENTY:religion', 'ENTY:sport', 'ENTY:substance', 'ENTY:symbol', 'ENTY:techmeth', 'ENTY:termeq', 'ENTY:veh', 'ENTY:word', 'DESC:def', 'DESC:desc', 'DESC:manner', 'DESC:reason', 'HUM:gr', 'HUM:ind', 'HUM:title', 'HUM:desc', 'LOC:city', 'LOC:country', 'LOC:mount', 'LOC:other', 'LOC:state', 'NUM:code', 'NUM:count', 'NUM:date', 'NUM:dist', 'NUM:money', 'NUM:ord', 'NUM:other', 'NUM:period', 'NUM:perc', 'NUM:speed', 'NUM:temp', 'NUM:volsize', 'NUM:weight']
['ABBR', 'ENTY', 'DESC', 'HUM', 'LOC', 'NUM']


In [20]:
from transformers import BertTokenizer,BertTokenizerFast

# Load BERT tokenizer
tokenizer = BertTokenizerFast.from_pretrained('bert-base-uncased')

# Function to tokenize the text
def tokenize_function(example):
    return tokenizer(example['text'], padding='max_length', truncation=True, max_length=64)

# Apply the tokenizer to the dataset
train_dataset = train_dataset.map(tokenize_function, batched=True)
test_dataset = test_dataset.map(tokenize_function, batched=True)

# Remove the original text columns (optional)
train_dataset = train_dataset.remove_columns(['text'])
test_dataset = test_dataset.remove_columns(['text'])

# Convert labels to TensorFlow format
train_dataset = train_dataset.with_format("tensorflow")
test_dataset = test_dataset.with_format("tensorflow")

Map: 100%|██████████| 500/500 [00:00<00:00, 10418.35 examples/s]


In [6]:
print("Versión de CUDA:", tf.sysconfig.get_build_info()["cuda_version"])
print("Versión de cuDNN:", tf.sysconfig.get_build_info()["cudnn_version"])

Versión de CUDA: 64_112
Versión de cuDNN: 64_8


In [5]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 9120492276557268230
xla_global_id: -1
]


In [2]:
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  0


In [2]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 12871954455675869555
xla_global_id: -1
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 2915486926
locality {
  bus_id: 1
  links {
  }
}
incarnation: 7408883155114554843
physical_device_desc: "device: 0, name: NVIDIA GeForce GTX 1050 Ti, pci bus id: 0000:01:00.0, compute capability: 6.1"
xla_global_id: 416903419
]


In [1]:
import tensorflow as tf

print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))

Num GPUs Available:  1


In [ ]:
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())

In [3]:
import tensorflow as tf

# Configurar TensorFlow para usar la primera GPU disponible
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
    try:
        tf.config.experimental.set_memory_growth(gpus[0], True)
        tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
        print("Using GPU: ", gpus[0])
    except RuntimeError as e:
        print(e)

Using GPU:  PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')


In [21]:
import tensorflow as tf

# Convert to TensorFlow datasets
train_features = {x: tf.convert_to_tensor(train_dataset[x]) for x in tokenizer.model_input_names}
train_labels = tf.convert_to_tensor(train_dataset['fine_label'])
train_dataset = tf.data.Dataset.from_tensor_slices((train_features, train_labels)).shuffle(1000).batch(16)

test_features = {x: tf.convert_to_tensor(test_dataset[x]) for x in tokenizer.model_input_names}
test_labels = tf.convert_to_tensor(test_dataset['fine_label'])
test_dataset = tf.data.Dataset.from_tensor_slices((test_features, test_labels)).batch(16)


In [22]:
from transformers import TFBertForSequenceClassification,TFDistilBertForSequenceClassification

# Load the BERT model for sequence classification
model = TFDistilBertForSequenceClassification.from_pretrained('distilbert-base-uncased', num_labels=50)

#model = TFBertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=50)




Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertForSequenceClassification: ['vocab_layer_norm.bias', 'vocab_transform.weight', 'vocab_layer_norm.weight', 'vocab_transform.bias', 'vocab_projector.bias']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
Some weights or buffers of the TF 2.0 model TFDistilBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['pre_classifier.weight', 'pre_classifier.bias', 'classifier.weight', 'classifier.bias']
You should 

In [24]:
ds_train

NameError: name 'ds_train' is not defined

In [28]:
train_labels

<tf.Tensor: shape=(5452,), dtype=int64, numpy=array([26,  5, 26, ..., 47, 47,  6], dtype=int64)>

In [29]:
print(train_features['input_ids'].shape)  # Asegúrate de que estas formas sean correctas
print(train_features['attention_mask'].shape)
print(train_labels.shape)

(5452, 64)
(5452, 64)
(5452,)


In [39]:
for inputs, labels in train_dataset.take(1):
    print(f"inputs: {inputs}")
    print(f"labels: {labels}")

inputs: {'input_ids': <tf.Tensor: shape=(16, 64), dtype=int64, numpy=
array([[ 101, 2054, 3146, ...,    0,    0,    0],
       [ 101, 2054, 2103, ...,    0,    0,    0],
       [ 101, 2054, 2003, ...,    0,    0,    0],
       ...,
       [ 101, 2054, 2024, ...,    0,    0,    0],
       [ 101, 2054, 2003, ...,    0,    0,    0],
       [ 101, 2129, 2116, ...,    0,    0,    0]], dtype=int64)>, 'attention_mask': <tf.Tensor: shape=(16, 64), dtype=int64, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int64)>}
labels: [32 32 47 26 39 26 25 13 11  7 13 39  5 20 24 38]


In [38]:
train_dataset

<BatchDataset element_spec=({'input_ids': TensorSpec(shape=(None, 64), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 64), dtype=tf.int64, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [32]:
train_labels = tf.convert_to_tensor(train_labels)
test_labels = tf.convert_to_tensor(test_labels)

# Eliminar 'token_type_ids' de los inputs, ya que DistilBERT no lo necesita
train_features = {key: value for key, value in train_features.items() if key != 'token_type_ids'}
test_features = {key: value for key, value in test_features.items() if key != 'token_type_ids'}

# Asegurarse de que los datasets estén en el formato correcto
train_dataset = tf.data.Dataset.from_tensor_slices((train_features, train_labels)).shuffle(1000).batch(16)
test_dataset = tf.data.Dataset.from_tensor_slices((test_features, test_labels)).batch(16)

In [40]:

# Compilar el modelo
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=2e-5),
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

# Entrenar el modelo
history = model.fit(
    train_dataset,
    epochs=3,
    batch_size=16,  # Ajustar según la memoria de tu GPU
    validation_data=test_dataset
)


Epoch 1/3
341/341 [==============================] - 118s 311ms/step - loss: 2.2806 - accuracy: 0.5163 - val_loss: 1.4076 - val_accuracy: 0.6860
Epoch 2/3
341/341 [==============================] - 103s 303ms/step - loss: 0.9121 - accuracy: 0.8081 - val_loss: 0.8941 - val_accuracy: 0.7980
Epoch 3/3
341/341 [==============================] - 103s 303ms/step - loss: 0.4821 - accuracy: 0.9006 - val_loss: 0.6555 - val_accuracy: 0.8500


In [44]:
import numpy as np
# Evaluar el modelo
loss, accuracy = model.evaluate(test_features, test_labels)
print(f'Loss: {loss}, Accuracy: {accuracy}')

# Predecir usando el modelo
predictions = model.predict(test_features)
predicted_labels = np.argmax(predictions.logits, axis=-1)

# Convertir predicciones numéricas de vuelta a etiquetas
#label_names = ds_info.features['label-coarse'].int2str
#predicted_labels = [label_names(label) for label in predicted_labels]
print("Predicted labels:", predicted_labels[:10])  # Muestra las primeras 10 predicciones

16/16 [==============================] - 3s 165ms/step - loss: 0.6555 - accuracy: 0.8500
Loss: 0.65546053647995, Accuracy: 0.8500000238418579
16/16 [==============================] - 3s 161ms/step
Predicted labels: [40 35 31 24 39 40 28  2 27 24]


In [50]:
fine_label_mapping = dataset['train'].features['fine_label'].names


In [55]:
test_dataset

<BatchDataset element_spec=({'input_ids': TensorSpec(shape=(None, 64), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, 64), dtype=tf.int64, name=None)}, TensorSpec(shape=(None,), dtype=tf.int64, name=None))>

In [51]:
predicted_label_names = [fine_label_mapping[label] for label in predicted_labels]
test_features
# Mostrar los resultados mapeados
for i in range(0,10):
print("Predicciones Numéricas:", predicted_labels[i])

print("Nombres de Etiquetas Mapeadas:", predicted_label_names)

Predicciones Numéricas: [40 35 31 24 39 40 28  2 27 24 32 29 43 29 39 44 18 29 24 39 29 24 35 24
 24 29 24 35 35 35 40 35 24 43 39 44 35 40 38 38  9 24 24 24 29 21 44 24
 38 28 24 29 29 24 25 24 39 32 35 43 32 29 35  9 36 31  2 24 39 35 43 41
 32 29 35 24 41 40 41 29 24 39 29 43 39 27 24 29 24 33 13 24 43 39 28 35
 39 24 24  8 24 29 26 31 35 24 43  2 39 35  4 24 40 29  2 29 39 18 39 35
 39 40 24 29 40 29 40 39 24 44 40 29 24 22 24 35 35 29 13 24 24  2 35 21
 24 13 29 22 24 24 21 29 24 39 28 35 32 24 35 36 24 24 39 35 21 35 39 24
 36 29 39 40 39 24 35 36 35 39  4 40 35 24 35 24 18 29 29 24 35 13 41 40
 44 39 24 32 41 29 13 18 22 32 29  2 43 35 29 43 25 25 39 40 36 35 24 11
 24 21 38 24 24 39 24 43 34 18 43 25 35 29 39 29 24 38 28 24 35 24 35 40
 36 24 27 24 24 35 24 24 25 25 29 24 13 18 24 35 40 21 24 41 29 29 38 13
 44 24 24 32 44 26 11 25 24 29 24 27 24 39  1 18 35 29  1 24 35 24 24 24
 24 24 32 24 44 21 24 24  4 44 13  4  1 39 24 39 39 35 29 35 29 39 32 35
 38 24 35 24 29 35  2 35 24

In [59]:
# Mostrar los textos originales y las predicciones
for idx in range(0,10):
    original_text = dataset['test'][idx]['text']
    original_label = dataset['test'][idx]['fine_label']
    label_name = dataset['train'].features['fine_label'].int2str(original_label)
    precition_number=predicted_labels[idx]
    precition_name=predicted_label_names[idx]
    print(f"Índice: {idx}")
    print(f"Texto original: {original_text}")
    print(f"Etiqueta Original Numérica: {precition_number}")
    print(f"Prediccion  Numérica: {original_label}")
    print(f"Etiqueta Original Nombre: {label_name}")
    print(f"Prediccion  Nombre: {precition_name}")
    
    print("=" * 50)

Índice: 0
Texto original: How far is it from Denver to Aspen ?
Etiqueta Original Numérica: 40
Prediccion  Numérica: 40
Etiqueta Original Nombre: NUM:dist
Prediccion  Nombre: NUM:dist
Índice: 1
Texto original: What county is Modesto , California in ?
Etiqueta Original Numérica: 35
Prediccion  Numérica: 32
Etiqueta Original Nombre: LOC:city
Prediccion  Nombre: LOC:other
Índice: 2
Texto original: Who was Galileo ?
Etiqueta Original Numérica: 31
Prediccion  Numérica: 31
Etiqueta Original Nombre: HUM:desc
Prediccion  Nombre: HUM:desc
Índice: 3
Texto original: What is an atom ?
Etiqueta Original Numérica: 24
Prediccion  Numérica: 24
Etiqueta Original Nombre: DESC:def
Prediccion  Nombre: DESC:def
Índice: 4
Texto original: When did Hawaii become a state ?
Etiqueta Original Numérica: 39
Prediccion  Numérica: 39
Etiqueta Original Nombre: NUM:date
Prediccion  Nombre: NUM:date
Índice: 5
Texto original: How tall is the Sears Building ?
Etiqueta Original Numérica: 40
Prediccion  Numérica: 40
Etiquet